version: '3'
services:
  etha-chat-redis:
    container_name: etha-chat-redis
    restart: always
    ports:
      - "6379:6379"
    image: redis
    command: redis-server --save 60 1 --loglevel warning
