name: ethachat-workflow
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: publish a project
        run: dotnet publish -r linux-x64 -o distro
        
      - name: build a Docker container
        run: docker build -t etha-web-app ./distro
        
      - name: tag image as latest
        run: docker tag etha-web-app:latest nlipatov/ethacore-ethachat:etha-web-app
        
      - name: push image to hub
        run: docker push nlipatov/ethacore-ethachat:etha-web-app
