name: ethachat-workflow
on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Setup .NET WASM build tools
        run: dotnet workload restore
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      publish_path: ${{ steps.publish_output.outputs.publish_path }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Setup .NET WASM build tools
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish with AOT
        id: publish_output
        run: |
          dotnet publish -c Release -r linux-x64 -o distro
          echo "publish_path=distro" >> $GITHUB_OUTPUT

  dockerhub-upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build a Docker container
        run: docker build -t etha-web-app ${{ needs.build.outputs.publish_path }}

      - name: Tag Docker image as latest
        run: docker tag etha-web-app:latest nlipatov/ethacore-ethachat:etha-web-app

      - name: Push image to hub
        run: docker push nlipatov/ethacore-ethachat:etha-web-app

  redeploy:
    runs-on: ubuntu-latest
    needs: dockerhub-upload
    steps:
      - name: Redeploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ethachat
            sudo docker compose pull && sudo docker compose up -d --remove-orphans --build && sudo docker system prune -f
